name: backend # workflow name

on: # trigger setting
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

defaults:
  run:
    working-directory: backend
  
jobs:
  build: # one job -> build
    runs-on: ubuntu-latest
    steps: # several steps
      - uses: actions/checkout@v3 # useful action from github actions
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci # execute command
      - run: npm run test -- --coverage
      - run: npm run build

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: backend/coverage/**
          retention-days: 5
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: backend/dist/index.js
          retention-days: 5